name: Manually re-build
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.13.0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.6.2'
          cache: 'pnpm'
      - name: Build
        run: |
          npx create-sveltepress-app create ./ --theme=GeopJr/cakepop
          pnpm i
          pnpm run build
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f .
          git commit -am "Bonk"
          git push https://github.com/GeopJr/cakepop HEAD:gh-pages -f
  
